import React, { useState } from 'react';
import { ShieldCheck, Sparkles, TrendingUp, AlertTriangle, CheckCircle2 } from 'lucide-react';

export default function PrescriptiveActions({ actions, onExecuteAction }) {
  const [filterType, setFilterType] = useState('All');

  // Filter actions list
  const filteredActions = filterType === 'All' 
    ? actions 
    : actions.filter(act => act.type === filterType);

  // Statistics
  const totalCount = actions.length;
  const executedCount = actions.filter(act => act.executed).length;
  const pendingCount = totalCount - executedCount;

  // Impact summation (mock valuation for premium dashboards)
  const totalProjectedImpact = actions.reduce((sum, act) => {
    let val = 0;
    if (act.type === 'Staffing') val = 800; // customer retention
    if (act.type === 'Marketing') val = 1500; // revenue boost
    if (act.type === 'Inventory') val = 1200; // waste savings
    if (act.type === 'Promotion') val = 600; // conversion lift
    return sum + (act.executed ? val : 0);
  }, 0);

  const getImpactBadgeClass = (impact) => {
    if (impact === 'High') return 'badge-high';
    if (impact === 'Medium') return 'badge-medium';
    return 'badge-low';
  };

  return (
    <div className="dashboard-viewport">
      {/* Prescriptive Actions Summary Card */}
      <div className="kpi-grid">
        <div className="kpi-card" style={{ gridColumn: 'span 2' }}>
          <div className="kpi-header">
            <span className="kpi-title">AI Optimization Summary</span>
            <div className="kpi-icon-wrapper" style={{ backgroundColor: 'var(--mcd-gold-glow)' }}>
              <Sparkles className="nav-icon" style={{ color: 'var(--mcd-gold)' }} />
            </div>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '20px', marginTop: '10px' }}>
            <div>
              <span style={{ fontSize: '11px', color: 'var(--text-secondary)', uppercase: true, display: 'block' }}>Projected Economic Value</span>
              <strong style={{ fontSize: '28px', color: 'var(--success)' }}>+${totalProjectedImpact.toLocaleString()}</strong>
            </div>
            <div style={{ width: '1px', height: '40px', backgroundColor: 'var(--border-color)' }} />
            <div>
              <span style={{ fontSize: '11px', color: 'var(--text-secondary)', display: 'block' }}>Operational Health</span>
              <strong style={{ fontSize: '18px', color: 'var(--mcd-gold)' }}>
                {executedCount} of {totalCount} Improvements Applied
              </strong>
            </div>
          </div>
        </div>

        <div className="kpi-card">
          <div className="kpi-header">
            <span className="kpi-title">Pending Decisions</span>
            <div className="kpi-icon-wrapper" style={{ backgroundColor: 'rgba(255,145,0,0.1)' }}>
              <AlertTriangle className="nav-icon" style={{ color: 'var(--warning)' }} />
            </div>
          </div>
          <div className="kpi-value" style={{ color: 'var(--warning)' }}>{pendingCount}</div>
          <div className="kpi-header" style={{ marginBottom: 0 }}>
            <span className="kpi-subtitle">Require manager deployment</span>
          </div>
        </div>

        <div className="kpi-card">
          <div className="kpi-header">
            <span className="kpi-title">System Execution Mode</span>
            <div className="kpi-icon-wrapper" style={{ backgroundColor: 'rgba(0,230,118,0.1)' }}>
              <ShieldCheck className="nav-icon" style={{ color: 'var(--success)' }} />
            </div>
          </div>
          <div className="kpi-value" style={{ fontSize: '20px', paddingTop: '8px' }}>Copilot (Semi-Auto)</div>
          <div className="kpi-header" style={{ marginBottom: 0 }}>
            <span className="kpi-subtitle">Human-in-the-loop validation</span>
          </div>
        </div>
      </div>

      {/* Main Actions Panel */}
      <div className="chart-card">
        <div className="chart-header">
          <div className="page-title-section">
            <h3 className="chart-title">Prescriptive Recommendation Feed</h3>
            <span className="page-subtitle">Actionable suggestions generated by the diagnostics module to resolve bottlenecks and capture revenue</span>
          </div>
          
          {/* Action category filter */}
          <div style={{ display: 'flex', gap: '8px' }}>
            {['All', 'Staffing', 'Marketing', 'Inventory', 'Promotion'].map((type) => (
              <button 
                key={type}
                className="filter-select"
                style={{ 
                  backgroundColor: filterType === type ? 'var(--mcd-gold)' : '', 
                  color: filterType === type ? '#000' : '' 
                }}
                onClick={() => setFilterType(type)}
              >
                {type}
              </button>
            ))}
          </div>
        </div>

        {/* Action Items Feed */}
        <div className="actions-layout">
          {filteredActions.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text-secondary)' }}>
              <CheckCircle2 size={48} style={{ color: 'var(--success)', marginBottom: '16px', opacity: 0.5 }} />
              <p style={{ fontWeight: '500' }}>No prescriptive recommendations available for this scope.</p>
              <p style={{ fontSize: '12px', marginTop: '4px' }}>All metrics fall within standard optimal performance thresholds.</p>
            </div>
          ) : (
            filteredActions.map((action) => (
              <div 
                key={action.id} 
                className={`action-item-card ${action.executed ? 'executed' : ''}`}
              >
                <div className="action-main-info">
                  <div className="action-meta">
                    <span className={`badge ${getImpactBadgeClass(action.impact)}`}>
                      {action.impact} Impact
                    </span>
                    <span style={{ color: 'var(--text-secondary)', fontSize: '12px', fontWeight: '600', textTransform: 'uppercase' }}>
                      {action.type}
                    </span>
                    {action.storeId !== 'All' && (
                      <span className="badge badge-none">
                        Store #{action.storeId}
                      </span>
                    )}
                  </div>
                  
                  <h4 className="action-title" style={{ marginTop: '8px' }}>{action.title}</h4>
                  
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginTop: '4px' }}>
                    <span style={{ color: 'var(--text-secondary)', fontSize: '12px' }}>Diagnostic trigger:</span>
                    <span className="action-metric-pill">{action.metric}</span>
                  </div>

                  <p className="action-desc">{action.recommendation}</p>
                </div>

                <div>
                  {action.executed ? (
                    <button className="action-btn success-state" disabled>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <CheckCircle2 size={16} />
                        Recommendation Deployed
                      </div>
                    </button>
                  ) : (
                    <button 
                      className="action-btn"
                      onClick={() => onExecuteAction(action.id)}
                    >
                      Deploy Optimization
                    </button>
                  )}
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
